#!/bin/sh
set -e

version="$1"
initramfs="$2"

echo "Post processing initrd: $initramfs"

if [ -e /boot/initrd.img-${version} ]; then
    ln -sf initrd.img-${version} /boot/initrd
    echo "Created symlink: /boot/initrd -> initrd.img-${version}"
else 
    echo "initrd.img-${version} must in /boot"
    echo "Add BOOTDIR=/boot in /etc/initramfs-tools/update-initramfs.conf"
    exit 1
fi

exit 0
